<?php
/**
 * Created by PhpStorm.
 * User: TurningTide
 * Date: 10.11.2017
 * Time: 8:04
 */
namespace frontend\components;

use yii\caching\TagDependency;

class Controller extends \yii\web\Controller{

    function init()
    {
        if(\Yii::$app->user->can('alphaTester')){
            $this->viewPath = '@frontend/viewsTest/'.$this->id;
            $this->layout = '@frontend/viewsTest/layouts/main';
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        if(empty($_GET['product'])){
            $tag = 'category_'.(!empty($_GET['id'])?$_GET['id']:null);
        } else {
            $tag = 'product_'.(!empty($_GET['product'])?$_GET['product']:null);
        }

        if(\Yii::$app->user->can('XAalphaTester')){
        $behaviors = [
            'pageCache' => [
                'class' => 'yii\filters\PageCache',
                'cache' => 'pageCache',
                'only' => ['category', 'actions', 'tagged', 'search'],
                'duration' => 86400,
                'dependency' => [
                    'class' => TagDependency::className(),
                    'tags' => $tag,
                ],
                'variations' => [
                    \Yii::$app->user->isGuest,
                    \Yii::$app->user->can('alphaTester'),
                    \Yii::$app->request->isAjax,
                    \Yii::$app->request->isPjax,
                    !empty(\Yii::$app->user->identity->customer->card),
                    !empty($_GET['id'])?$_GET['id']:null,
                    !empty($_GET['monufacturer'])?$_GET['monufacturer']:null,
                    !empty($_GET['tag'])?$_GET['tag']:null,
                    !empty($_GET['SCCategoriesSearch'])?$_GET['SCCategoriesSearch']:null,
                    !empty($_GET['SCCategoriesSearchMicro'])?$_GET['SCCategoriesSearchMicro']:null,
                    !empty($_GET['product'])?$_GET['product']:null,
                    !empty($_GET['sort'])?$_GET['sort']:null,
                    !empty($_GET['onlyAvailable'])?$_GET['onlyAvailable']:null,
                    !empty($_GET['onlyActions'])?$_GET['onlyActions']:null,
                ]
            ],
        ];
        } else {
            $behaviors = [];
        }


        return array_merge($behaviors,parent::behaviors()); // TODO: Change the autogenerated stub
    }
}