<?php

namespace common\models;

use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "SC_mainpage".
 *
 * @property integer $id
 * @property string $picture
 * @property string $url
 * @property integer $fieldset
 * @property integer $x
 * @property integer $y
 * @property integer $width
 * @property integer $height
 */
class SCMainpage extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'SC_mainpage';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['url', 'fieldset'], 'required'],
            [['fieldset', 'x', 'y', 'width', 'height'], 'integer'],
            [['picture', 'url'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'picture' => 'Картинка',
            'url' => 'Ссылка',
            'fieldset' => 'Fieldset',
            'x' => 'X',
            'y' => 'Y',
            'width' => 'Width',
            'height' => 'Height',
        ];
    }

    public function afterFind()
    {
        if(!empty($this->url)){
            $parts = parse_url($this->url);
            parse_str($parts['query'], $query);
            if (strpos($this->url, 'static') !== false){
                $this->url = Url::to(['/brands/index', 'alias'=>$query['static']]);
            } elseif (strpos($this->url, 'categoryID') !== false){
                $this->url = Url::to(['/shop/category', 'id'=>$query['categoryID']]);
            }
        }

        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
