<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "SC_news_table".
 *
 * @property integer $NID
 * @property string $add_date
 * @property string $title_en
 * @property string $title_ru
 * @property string $picture
 * @property string $textToPublication_en
 * @property string $textToPublication_ru
 * @property string $textToMail
 * @property integer $add_stamp
 * @property integer $priority
 * @property integer $emailed
 * @property integer $published
 * @property integer $brand
 * @property string $textMini
 * @property string $textPreview
 * @property string $tpl
 */
class SCNewsTable extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'SC_news_table';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title_en', 'title_ru', 'textToPublication_en', 'textToPublication_ru', 'textToMail', 'textMini', 'textPreview', 'tpl'], 'string'],
            [['add_stamp', 'priority', 'emailed', 'brand', 'published'], 'integer'],
            [['created_at', 'updated_at', 'published_at'], 'integer'],
            [['add_date'], 'string', 'max' => 30],
            [['picture'], 'string', 'max' => 3000],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'NID' => 'Nid',
            'add_date' => 'Дата добавления',
            'title_en' => 'Title En',
            'title_ru' => 'Заголовок',
            'picture' => 'Картинка',
            'textToPublication_en' => 'Text To Publication En',
            'textToPublication_ru' => 'Текст новости',
            'textToMail' => 'Text To Mail',
            'add_stamp' => 'Add Stamp',
            'priority' => 'Priority',
            'emailed' => 'Emailed',
            'brand' => 'Привязка к бренду',
            'textMini' => 'Краткий текст',
            'textPreview' => 'Text Preview',
            'published' => 'Статус',
        ];
    }

    public function getDate(){
        if (date('Y-m-d') == date('Y-m-d', strtotime($this->add_date))) {
            return 'Сегодня в '.date('H:i', strtotime($this->add_date));
        } elseif(date('Ymd', strtotime($this->add_date)) == date('Ymd', strtotime('yesterday'))){
            return 'Вчера в '.date('H:i', strtotime($this->add_date));
        } else {
            if(date('Y') > date('Y', strtotime($this->add_date))){
                return $this->replaceMonth(date('d F Y в H:i', strtotime($this->add_date)));
            } else {
                return $this->replaceMonth(date('d F в H:i', strtotime($this->add_date)));
            }
        }
    }


    function replaceMonth($date){
        $date = str_replace('January', 'Января', $date);
        $date = str_replace('February', 'Февраля', $date);
        $date = str_replace('March', 'Марта', $date);
        $date = str_replace('April', 'Апреля', $date);
        $date = str_replace('May', 'Мая', $date);
        $date = str_replace('June', 'Июня', $date);
        $date = str_replace('July', 'Июля', $date);
        $date = str_replace('August', 'Августа', $date);
        $date = str_replace('September', 'Сентября', $date);
        $date = str_replace('October', 'Октября', $date);
        $date = str_replace('November', 'Ноября', $date);
        $date = str_replace('December', 'Декабря', $date);

        return $date;
    }

    public function getMonufacturer(){
        return SCMonufacturers::findOne($this->brand);
    }

    public function getImage()
    {
        $fileExtension =  pathinfo($this->picture, PATHINFO_EXTENSION);
        $fileName =  pathinfo($this->picture, PATHINFO_FILENAME);
        return $fileName.'.'.$fileExtension;
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->created_at = time();
        }
        $this->updated_at = time();
        $this->add_date = date('d.m.Y h:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($insert){
            if($this->published == 1) $this->published_at = time();
            $this->save();
        } else {
            if($this->published == 1 && empty($this->published_at)){
                $this->published_at = time();
                $this->save();
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
