<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "SC_product_options".
 *
 * @property integer $optionID
 * @property integer $sort_order
 * @property string $name_en
 * @property string $name_ru
 * @property string $slider_step
 * @property string $optionType
 * @property string $optionCategory
 * @property string $description_title_en
 * @property string $description_text_en
 * @property string $slider_prefix_en
 * @property string $description_title_ru
 * @property string $description_text_ru
 * @property string $slider_prefix_ru
 * @property integer $filter
 * @property integer $dropdown
 * @property string $filterType
 * @property string $filterStep
 */
class SCProductOptions extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'SC_product_options';
    }

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('db');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sort_order', 'filter', 'dropdown'], 'integer'],
            [['description_title_en', 'description_text_en', 'slider_prefix_en', 'description_title_ru', 'description_text_ru', 'slider_prefix_ru', 'filterStep'], 'string'],
            [['name_en', 'name_ru'], 'string', 'max' => 50],
            [['slider_step', 'optionType', 'optionCategory'], 'string', 'max' => 45],
            [['filterType'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'optionID' => 'Option ID',
            'sort_order' => 'Sort Order',
            'name_en' => 'Name En',
            'name_ru' => 'Name Ru',
            'slider_step' => 'Slider Step',
            'optionType' => 'Option Type',
            'optionCategory' => 'Option Category',
            'description_title_en' => 'Description Title En',
            'description_text_en' => 'Description Text En',
            'slider_prefix_en' => 'Slider Prefix En',
            'description_title_ru' => 'Description Title Ru',
            'description_text_ru' => 'Description Text Ru',
            'slider_prefix_ru' => 'Slider Prefix Ru',
            'filter' => 'Фильтровать по этому атрибуту',
            'dropdown' => 'Dropdown',
            'filterType' => 'Тип фильтра',
            'filterStep' => 'Шаг',
        ];
    }

    public function nameAttr($id){
        $model = SCProductOptions::find()->where("optionID = $id")->one();
        return $model->name_ru;
    }

    public function afterFind()
    {
        if($this->name_ru == 'RUSIZE'){
            $this->name_ru = 'Размер (Русский)';
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
