<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "subscribed_mails".
 *
 * @property integer $id
 * @property string $email
 */
class SubscribedMails extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'subscribed_mails';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'emailTrim'     => ['email', 'trim'],
            'emailRequired' => ['email', 'required'],
            'emailPattern'  => ['email', 'email'],
            'emailUnique'   => [
                'email',
                'unique',
                'targetClass' => SubscribedMails::className(),
                'message' => "Этот email уже подписан"
            ],
            [['unsubscribehash'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email' => 'Email',
        ];
    }

    public function beforeSave($insert)
    {
        if($insert){
            $this->unsubscribehash = md5(uniqid().$this->email.time());
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
