<?php
/**
 * Created by PhpStorm.
 * User: TurningTide
 * Date: 24.08.2017
 * Time: 12:53
 */

namespace frontend\actions;

class CaptchaAction extends \yii\captcha\CaptchaAction
{
    protected function generateVerifyCode()
    {
        return parent::generateVerifyCode(); // TODO: Change the autogenerated stub
    }
}