<?php
/**
 * Created by PhpStorm.
 * User: TurningTide
 * Date: 26.07.2017
 * Time: 11:36
 */

namespace common\behaviors;

use yii\base\Behavior;
use yii\db\ActiveRecord;
use yii\web\View;

class UnifyBehavior extends Behavior
{
    public $object_name;
    public $name;
    public $object_type;
    public $type;
    public $fieldTypes = [];

    public function events()
    {
        return [
            ActiveRecord::EVENT_AFTER_FIND => 'loadAttrs',
        ];
    }

    public function loadAttrs($event)
    {
        $this->owner->name_ru = "asd";
    }

    /*public function init()
    {
        if(!empty($this->owner)){
            $this->object_name = $this->owner::className();
        }
        parent::init(); // TODO: Change the autogenerated stub
    }*/
}